INSERT INTO CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Notebook');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Smartphone');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL, 'TV');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Tablet');

INSERT INTO MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'LG');
INSERT INTO MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'Apple');
INSERT INTO MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'Samsumg');
INSERT INTO MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'Sony');

INSERT INTO PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, ID_MARCA) VALUES (PRODUTO_SEQ.NEXTVAL, 'Nome do produto 1', 'sku-0001', 'Descrição do Produto 1', 'Características do produto 1', 1.99, sysdate , 1, 1);
INSERT INTO PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, ID_MARCA) VALUES (PRODUTO_SEQ.NEXTVAL, 'Nome do produto 2', 'sku-0002', 'Descrição do Produto 2', 'Características do produto 2', 2.99, sysdate , 2, 2);
INSERT INTO PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, ID_MARCA) VALUES (PRODUTO_SEQ.NEXTVAL, 'Nome do produto 3', 'sku-0002', 'Descrição do Produto 3', 'Características do produto 3', 3.99, sysdate , 3, 3);
INSERT INTO PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, ID_MARCA) VALUES (PRODUTO_SEQ.NEXTVAL, 'Nome do produto 4', 'sku-0002', 'Descrição do Produto 4', 'Características do produto 4', 4.99, sysdate , 4, 4);
INSERT INTO PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, ID_MARCA) VALUES (PRODUTO_SEQ.NEXTVAL, 'Nome do produto 5', 'sku-0005', 'Descrição do Produto 5', 'Características do produto 5', 4.99, sysdate , 4, 4);
INSERT INTO PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, ID_MARCA) VALUES (PRODUTO_SEQ.NEXTVAL, 'Nome do produto 6', 'sku-0006', 'Descrição do Produto 6', 'Características do produto 6', 4.99, sysdate , 4, 4);

INSERT INTO LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Americanas');
INSERT INTO LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Fast Shop');
INSERT INTO LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Magazine Luiza');
INSERT INTO LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Submarino');