CREATE TABLE CIENTISTA (
    CODIGO NUMBER(4) CONSTRAINT PK_CIE_CODIGO PRIMARY KEY,
    NOME VARCHAR2(50) CONSTRAINT NN_CIE_NOME NOT NULL,
    DT_NASC DATE,
    SEXO CHAR(1) CONSTRAINT CK_CIE_SEX CHECK (SEXO IN ('F', 'M', 'f', 'm'))
)

INSERT INTO CIENTISTA 
VALUES (1010, 'STEPHEN HAWKING', '08/01/1942', 'M');

INSERT INTO CIENTISTA 
VALUES (1011, 'ALBERT EINSTEIN', '14/03/1879', 'M');
       
INSERT INTO CIENTISTA        
VALUES (1012, 'ISAAC NEWTON', '04/01/1643', 'M');
       
INSERT INTO CIENTISTA        
VALUES (1013, 'GALILEU GALILEI', '15/02/1564', 'M');
       
INSERT INTO CIENTISTA        
VALUES (1014, 'NICOLAU COPERNICO', '19/02/1473', 'M');      

COMMIT;

SELECT * FROM CIENTISTA;

CREATE TABLE CLIENTE(
    CODIGO NUMBER(4) CONSTRAINT PK_CLIENTE_CODIGO PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL
)

---INSERINDO COM SELECT
INSERT INTO CLIENTE
SELECT CODIGO, NOME FROM CIENTISTA;

COMMIT;

SELECT * FROM CLIENTE;

---Criar coluna nova na tabela Cientista chamada DT_OBTO do tipo Date
ALTER TABLE CIENTISTA
    ADD DT_OBTO DATE;

DESCRIBE CIENTISTA

--Atualizar todoso os registros da tabela com a data de óbito de cada cientista
UPDATE CIENTISTA 
    SET DT_OBTO = '14/05/2018'
    WHERE CODIGO = 1010;

UPDATE CIENTISTA
    SET DT_OBTO = '18/04/1955'
    WHERE CODIGO = 1011;
    
UPDATE CIENTISTA 
    SET DT_OBTO = '31/03/1727'
    WHERE CODIGO = 1012;
    
    
UPDATE CIENTISTA 
    SET DT_OBTO = '08/01/1642'
    WHERE CODIGO = 1013 AND NOME = 'GALILEU GALILEI';
    
    
UPDATE CIENTISTA 
    SET DT_OBTO = '24/05/1543'
    WHERE CODIGO = 1014 AND NOME = 'NICOLAU COPERNICO';    

SELECT * FROM CIENTISTA;

COMMIT;

---Remover o primeiro nome (mantendo apenas o sobrenome) do campo Nome, dos cientistas com os códigos iguais a 1011 e 1012
UPDATE CIENTISTA
    SET NOME = 'EINSTEIN' 
WHERE CODIGO = 1011;
    
UPDATE CIENTISTA
    SET NOME = 'NEWTON' 
WHERE CODIGO = 1012;

SELECT * FROM CIENTISTA;

COMMIT;

---UPDATE COM SELECT
---Criar uma coluna nova na tabela Cliente chamada DT_NASC do tipo Date
ALTER TABLE CLIENTE
    ADD DT_NASC DATE;

DESCRIBE CLIENTE

---Atualizar todos os registros da tabela Cliente com a data de Nascimento de cada Cientista. Ps: Combinar o comando SELECT com UPDATE
SELECT * FROM CLIENTE;

ROLLBACK;

UPDATE CLIENTE
    SET DT_NASC = (SELECT DT_NASC FROM CIENTISTA WHERE CLIENTE.CODIGO = CIENTISTA.CODIGO);

SELECT * FROM CLIENTE;

COMMIT;


---DELETE
---Remover todos os Cientistas que não nasceram no mês de Fevereiro
SELECT * FROM CIENTISTA;
ROLLBACK;

DELETE FROM CIENTISTA WHERE TO_CHAR(DT_NASC, 'MONTH') <> 'FEVEREIRO';
---OR
DELETE FROM CIENTISTA 
    WHERE EXTRACT(MONTH FROM DT_NASC) !=2;

SELECT * FROM CIENTISTA;

COMMIT;

---DELETE COM SELECT
---Apagar todos os Clientes que não estão na tabela Cientista utilizando os comandos DELETE e SELECT
SELECT * FROM CLIENTE;
ROLLBACK;

DELETE FROM CLIENTE
    WHERE CODIGO NOT IN (SELECT CODIGO FROM CIENTISTA);

COMMIT;


