--DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
--DROP TABLE MATERIA_PRIMA CASCADE CONSTRAINTS;
--DROP TABLE PRODUTO CASCADE CONSTRAINTS;
--DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE CATEGORIA (
    COD_CATEGORIA NUMBER(5) CONSTRAINT PK_CATEGORIA_COD_CATEGORIA PRIMARY KEY,
    CATEGORIA VARCHAR2(255) UNIQUE CHECK (CATEGORIA IN ('DOCE', 'BEBIDA', 'CONGELADO'))
)

CREATE TABLE MATERIA_PRIMA(
    COD_MATERIA_PRIMA NUMBER(5) CONSTRAINT PK_MATERIA_PRIMA_COD_MAT_PRI PRIMARY KEY,
    MATERIA_PRIMA VARCHAR2(255)UNIQUE
)

CREATE TABLE PRODUTO(
    COD_PRODUTO NUMBER(5) CONSTRAINT PK_PRODUTO_COD_PROD PRIMARY KEY,
    COD_CATEGORIA CONSTRAINT FK_PRODUTO_COD_CATEGORIA REFERENCES CATEGORIA(COD_CATEGORIA),
    PRODUTO VARCHAR2(255) UNIQUE
)

CREATE TABLE ITEM_PRODUTO(
    COD_PRODUTO NUMBER(5) CONSTRAINT FK_ITEM_PRODUTO_COD_PROD REFERENCES PRODUTO(COD_PRODUTO),
    COD_MATERIA_PRIMA NUMBER(5) CONSTRAINT FK_ITEMP_PRODUTO_COD_MAT_PRI REFERENCES MATERIA_PRIMA(COD_MATERIA_PRIMA),
    QUANTIDADE NUMBER(5) NOT NULL
)