ALTER TABLE ITEM_PRODUTO
ADD TIPO_MEDIDA VARCHAR2(30) CHECK (TIPO_MEDIDA IN('LITRO', 'KILO', 'UNIDADE'));

DESCRIBE ITEM_PRODUTO;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('ITEM_PRODUTO');

CREATE SEQUENCE SEQ_CATEGORIA;

INSERT INTO CATEGORIA (COD_CATEGORIA, CATEGORIA)
VALUES (SEQ_CATEGORIA.NEXTVAL, 'DOCE'),
       (SEQ_CATEGORIA.NEXTVAL, 'BEBIDA'),
       (SEQ_CATEGORIA.NEXTVAL, 'CONGELADO');
       
SELECT * FROM CATEGORIA;
